[package]
name = "ca-sdk"
version = "1.0.0"
authors = [ "Kromsten <s@noreply.megarock.labs>" ]
edition = "2021"


[features]
default = []

[dependencies]
cosmwasm-std     = { workspace = true }
cosmwasm-storage = { workspace = true }
secret-toolkit   = { workspace = true }
thiserror        = { workspace = true }
cosmwasm-schema  = { workspace = true }
bech32           = { workspace = true }
sha2             = { workspace = true }

ripemd           = { version = "0.1.3",  default-features = false }
cw-utils         = { version = "2.0.0"  }