[package]
name = "ca-sdk"
version = "1.0.0"
authors = [ "Kromsten <s@noreply.megarock.labs>" ]
edition = "2021"


[features]
default   = ["common", "gateway"]
common    = ["wallets"]
wallets   = ["dep:bip32"]
funds     = ["dep:serde-cw-value"]
gateway   = []


[dependencies]
cosmwasm-schema  = { workspace = true }
bech32           = { workspace = true }

cosmwasm-std     = { package = "secret-cosmwasm-std", version = "1.1.11", features = ["random", "stargate"] }
cosmwasm-storage = { package = "secret-cosmwasm-storage", version = "1.1.11" }

secret-toolkit   = { version = "0.10.0", default-features = false, features = [
    "viewing-key", "crypto", "permit", "storage", "utils", "snip20"
]}



ripemd           = { version = "0.1.3",  default-features = false }
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["alloc"] }
secp256k1        = { version = "0.29.0", default-features = false, features = ["alloc"] }

bip32            = { version = "0.5.1", default-features = false, features = ["mnemonic", "bip39", "secp256k1"], optional = true }
serde            = { version = "1.0.137", default-features = false, features = ["derive"] }

serde-cw-value   = { version = "0.7.0", optional = true }
