
export const {
    SECRET_MNEMONIC,
    SECRET_CHAIN_ENDPOINT,
    SECRET_CHAIN_ID,
    SECRET_TOKEN,
    CONSUMER_MNEMONIC,
    CONSUMER_CHAIN_ENDPOINT,
    CONSUMER_CHAIN_ID,
    CONSUMER_TOKEN,
    CONSUMER_PREFIX,
    CONSUMER_GAS_PRICE,
    CONSUMER_DECIMALS,
} = process.env